### PR TITLE
Many updates - primarily header-related

### PR DESCRIPTION
**Pull request by fhgwright**
See the individual commit descriptions for more details.  Note that the first commit is purely cosmetic and accounts for 12 of the changed files.

Tested on:
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H15, x86_64, Xcode 12.4 12D4e
macOS 11.7.10 20G1427, x86_64, Xcode 13.2.1 13C100
macOS 11.7.10 20G1427, arm64, Xcode 13.2.1 13C100
macOS 12.7.5 21H1222, x86_64, Xcode 14.2 14C18
macOS 12.7.5 21H1222, arm64, Xcode 14.2 14C18
macOS 13.6.7 22G720, arm64, Xcode 15.2 15C500b
macOS 14.5 23F79, arm64, Xcode 15.4 15F31d
```

This requires removing most of the Tiger-specific hackery in the Portfile.  Originally I thought that that would be optional, but the copying gets an error when there's nothing to copy.  It's easier to remove the affected code than to fix it.  The corresponding -devel port will need to fork the Tiger-specific code into two versions, to be reunified in a simpler form as of the next release version.

### CODE REVIEW

**Comment by fhgwright** [comment]
@mascguy 
Notifying manually.

I just force-pushed a fix for a minor naming inconsistency (that wouldn't have mattered in practice).

**Comment by fhgwright** [comment]
@mascguy 
I just force-pushed some commit-message updates, mainly to add ticket references where appropriate.  No code changes.

**Comment by mascguy** [comment]
> I just force-pushed some commit-message updates, mainly to add ticket references where appropriate.  No code changes.

No worries.

I'll try to review everything over the next few days, if possible.

**Comment by fhgwright** [comment]
@mascguy 
I just added one more commit, which is a simple addition to the Makefile to further simplify the Tiger-specific hackery in the Portfile.  Getting it into this batch avoids an extra round of tweaking of that aspect of the Portfile, which now becomes very simple.

In doing this, I realized that I'd forgotten to declare the new clean targets as .PHONY.  It's not that important in this case, but worth doing for consistency.  Since it makes sense to do that in the same commits as the ones that added the targets, I amended the existing commits accordingly, which of course required a forced push.

The overall result is 13 lines added to the Makefile, 12 of which are from the new commit.  No other changes.

**Review by mascguy — APPROVED** [review]
I tried to review as much of the detail as possible, within the confines of an hour.

Looks great to me.

**Pull request merged**
