### PR TITLE
Several updates - see individual commits

### PR DESCRIPTION
**Pull request by fhgwright**
Notably:

- The darwin_c tests are now included in the automatic tests.
- Works around Apple's broken versioning in the macOS 15 SDK.
- Implements scandir() compatibility feature.
- Fixes dprintf() bug and implements vdprintf().

Tested on:
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H15, x86_64, Xcode 12.4 12D4e
macOS 11.7.10 20G1427, x86_64, Xcode 13.2.1 13C100
macOS 11.7.10 20G1427, arm64, Xcode 13.2.1 13C100
macOS 12.7.6 21H1320, x86_64, Xcode 14.2 14C18
macOS 12.7.6 21H1320, arm64, Xcode 14.2 14C18
macOS 13.7 22H123, arm64, Xcode 15.2 15C500b
macOS 14.7 23H124, arm64, Xcode 16.0 16A242d
macOS 15.0 24A335, arm64, Xcode 16.0 16A242d
```

### CODE REVIEW

**Comment by fhgwright** [comment]
@mascguy 
Here's your manual notification. :-)
Part of this supersedes #95, as previously discussed there.  It should be closed.

@macportsraf
I came up with a way to avoid the `dup()` and the related lock problem.  See the big comment.

**Comment by fhgwright** [comment]
@mascguy 
Ping.

**Comment by fhgwright** [comment]
@mascguy 
Ah, you're alive. :-)

I have another bunch of changes coming, but my intent is to make this round into a -devel version first.  The next round is mostly about cleaning up after SDK 15, which has really proved to be the gift that keeps on giving (and not in a good way).

**Comment by fhgwright** [comment]
@mascguy 
If you don't have time to review this, maybe there's someone else who does.  This is over three weeks old now, and my post to the ML didn't accomplish anything other than getting the obsolete PR closed.

**Comment by macportsraf** [comment]
@fhwright I don't see an explanation why a local buffer is used in `dprintf`. Could the reason be documented? Or have I missed it? I would have thought that `fdopen` would create a buffer. Is there a problem with using that one?

**Comment by fhgwright** [comment]
@macportsraf 
> @fhwright I don't see an explanation why a local buffer is used in `dprintf`. Could the reason be documented? Or have I missed it? I would have thought that `fdopen` would create a buffer. Is there a problem with using that one?

It's better to get the free allocation on the stack than to go through `malloc()` and `free()`, which would also require additional internal knowledge of `FILE` to find the buffer address.  Note that Apple's code does the same thing.

Apple's code also uses the stack for the `FILE`, but that requires way more internal knowledge than this code is assuming.  It's trying to use the bare minimum of internal knowledge necessary to accomplish the goal, which is to avoid _both_ closing the underlying fd _and_ releasing any locks that may be in effect.

**Comment by fhgwright** [comment]
@macportsraf 
Actually, upon reflection, I think the `fclose()` would handle the `free()`.  But it still wouldn't make sense to incur the `malloc()/free()` overhead just to avoid a modest-sized buffer on the stack.  The reason one can't use `free()` on a `FILE` is that `FILE` uses a special allocator just to avoid the `malloc()/free()` overhead.

**Review by mascguy — APPROVED** [review]
Sorry for the delay. LGTM, great work as always folks!

**Pull request merged**
