### PR TITLE
Add two new queue macros with tests, plus a warning fix.

### PR DESCRIPTION
**Pull request by fhgwright**
See the individual commit messages.

### CODE REVIEW

**Comment by fhgwright** [comment]
@mascguy 
This should be a much easier review than the last one. :-)

**Comment by mascguy** [comment]
> @mascguy 
> This should be a much easier review than the last one. :-)

Yes indeed, and looks good to me.

**Review by mascguy — APPROVED** [review]

**Comment by fhgwright** [comment]
I'll wait until an appropriately updated #93 is also merged before making another -devel update.  This completes what I'd planned for this release cycle, so the next -devel will probably be an RC.  With the extent of the changes, it might be a good idea to call for wider testing at that point.

**Comment by mascguy** [comment]
> I'll wait until an appropriately updated #93 is also merged before making another -devel update.  This completes what I'd planned for this release cycle, so the next -devel will probably be an RC.  With the extent of the changes, it might be a good idea to call for wider testing at that point.

Sounds good. And agreed, wider testing would be a good thing.

**Pull request merged**
