### PR TITLE
Update copyright years

### PR DESCRIPTION
**Pull request by aeiouaeiouaeiouaeiouaeiouaeiou**

### CODE REVIEW

**Comment by fhgwright** [comment]
This is not legally necessary, though it doesn't hurt.

**Comment by fhgwright** [comment]
@mascguy 
I don't have a problem in principle with merging this, though its importance is overestimated, but I don't want to do it until after the release, just to avoid rocking the boat.

I do wonder why someone who wants to remain anonymous is concerned about copyright. :-)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I don't see anything wrong with remaining anonymous and why I can't do PR for cosmetic fixes.

**Review by mascguy — APPROVED** [review]

**Comment by mascguy** [comment]
Now that we have a new release of legacy-support, let's go ahead and merge this.

**Pull request merged**
