### PR TITLE
Revert "support new symbol names on older systems"

### PR DESCRIPTION
**Pull request by fhgwright**
This reverts commit a1e2bb0b1bc62585cd2c5abf09cfea24c28600fe.

That commit caused broken builds on 10.6 and 10.7.

TESTED:
Now builds and passes tests on 10.4-10.5 ppc, 10.4-10.6 i386, 10.5-12.x x86_64, and 11.x-14.x arm64.

### CODE REVIEW

**Comment by fhgwright** [comment]
Back to the drawing board for that one.

**Comment by mascguy** [comment]
> This reverts commit a1e2bb0b1bc62585cd2c5abf09cfea24c28600fe.
> That commit caused broken builds on 10.6 and 10.7.

@MarcusCalhoun-Lopez Are these build issues easily fixed, such that you can address via another PR?

If so, that would be preferable to simply reverting these changes.

**Comment by kencu** [comment]
Isn’t it just missing a definition for NULL on some systems?

If so, trivial fix.

**Comment by fhgwright** [comment]
It was a different error on 10.7, but I didn't keep a copy since my priority was to undo the damage ASAP and *then* figure out the proper fix.

**Comment by MarcusCalhoun-Lopez** [comment]
Thank you for finding this error.
For some reason, it did not show up when I tested it on 10.5.
It should be fixed in #81, so I do not believe there is a reason to revert the change.

> It was a different error on 10.7, but I didn't keep a copy since my priority was to undo the damage ASAP and _then_ figure out the proper fix.

For me, #81 seemed to fix the problem on 10.7.
If you could provide the separate 10.7 error, that would be very helpful.

**Comment by mascguy** [comment]
> Thank you for finding this error. For some reason, it did not show up when I tested it on 10.5. It should be fixed in #81, so I do not believe there is a reason to revert the change.
> 
>> It was a different error on 10.7, but I didn't keep a copy since my priority was to undo the damage ASAP and _then_ figure out the proper fix.
> 
> For me, #81 seemed to fix the problem on 10.7. If you could provide the separate 10.7 error, that would be very helpful.

Marcus' latest fix has been merged, and the buildbot failures for 10.6/10.7 appear to be resolved.

Can you folks confirm whether you're still seeing issues, with the latest release of `legacy-support-devel`?

**Comment by fhgwright** [comment]
@mascguy @MarcusCalhoun-Lopez 
> Marcus' latest fix has been merged, and the buildbot failures for 10.6/10.7 appear to be resolved.
> 
> Can you folks confirm whether you're still seeing issues, with the latest release of `legacy-support-devel`?

I'll test it, but I don't expect to have time today.

**Comment by fhgwright** [comment]
It once again builds and passes tests in all configurations I've tested except for the usual build failure on 10.4 ppc +universal.

Tested configurations are:
```
Mac OS X 10.4.11 8S165, PPC, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, i386, Xcode 2.5 8M2558
Mac OS X 10.4.11 8S2167, x86_64, Xcode 2.5 8M2558
Mac OS X 10.5.8 9L31a, PPC, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, i386, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, x86_64, Xcode 3.1.4 9M2809
Mac OS X 10.5.8 9L31a, PPC (i386 Rosetta), Xcode 3.1.4 9M2809
Mac OS X 10.6.8 10K549, i386, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, x86_64, Xcode 3.2.6 10M2518
Mac OS X 10.6.8 10K549, PPC (i386 Rosetta), Xcode 3.2.6 10M2518
Mac OS X 10.7.5 11G63, x86_64, Xcode 4.6.3 4H1503
OS X 10.8.5 12F2560, x86_64, Xcode 5.1.1 5B1008
OS X 10.9.5 13F1911, x86_64, Xcode 6.2 6C131e
OS X 10.10.5 14F2511, x86_64, Xcode 7.2 7C68
OS X 10.11.6 15G22010, x86_64, Xcode 8.1 8B62
macOS 10.12.6 16G2136, x86_64, Xcode 9.2 9C40b
macOS 10.13.6 17G14042, x86_64, Xcode 10.1 10B61
macOS 10.14.6 18G9323, x86_64, Xcode 11.3.1 11C505
macOS 10.15.7 19H15, x86_64, Xcode 12.4 12D4e
macOS 11.7.10 20G1427, x86_64, Xcode 13.2.1 13C100
macOS 11.7.10 20G1427, arm64, Xcode 13.2.1 13C100
macOS 12.7.4 21H1123, x86_64, Xcode 14.2 14C18
macOS 12.7.4 21H1123, arm64, Xcode 14.2 14C18
macOS 13.6.5 22G621, arm64, Xcode 15.2 15C500b
macOS 14.4 23E214, arm64, Xcode 15.3 15E204a
```

One of the reasons I volunteered to be co-maintainer on this project is because I have the ability to test on almost all configurations.  But that's of limited value when changes are merged before I even hear about them, let alone have a chance to test them.

**Pull request closed without merging**
