### PR TITLE
clock_gettime: added missing CLOCK_*

### PR DESCRIPTION
**Pull request by catap**

### CODE REVIEW

**Comment by catap** [comment]
@mascguy , @kencu may I ask you to review this one?

I need it to simplify https://github.com/macports/macports-ports/pull/18929

Thanks!

**Comment by catap** [comment]
@mascguy quite trivial and very annoyed :)

**Comment by catap** [comment]
@mascguy quite trivial and allows to remove wired bugs which we're introducing by redefined missed clocks which isn't supported by our clock_gettime.

**Comment by mascguy** [comment]
I recently had to patch `libfaketime` to deal with some of these missing constants, but these additions should eliminate the need for that:

https://github.com/macports/macports-ports/commit/06c793df1cde1faf718a493e84e6de936d27a53a

Great stuff Kirill!

**Comment by catap** [comment]
@mascguy we have some patches which recovers original values which leads to error instead of some times. If code trusts systemcalls... 

See https://github.com/macports/macports-ports/blob/929224823b022cf995e14f4e34f75f3342ec6436/science/osmocore/files/patch-fix_clock_gettime.devel.diff#L436-L444 for example.

**Comment by jmroot** [comment]
This doesn't look correct. `CLOCK_MONOTONIC_RAW_APPROX` is the only one that's somewhat reasonable, but even that is supposed to be faster than a syscall. The other clocks are supposed to behave quite differently.

**Comment by jmroot** [comment]
Ah I see, the existing code is actually incorrect for `CLOCK_MONOTONIC` but correct for `CLOCK_UPTIME_RAW`. But the `CPUTIME` clocks are still measuring something totally different.

**Comment by catap** [comment]
@jmroot anyway, wrong value which increases is much better than error or no value, isn't it?

**Comment by cjones051073** [comment]
> This doesn't look correct. `CLOCK_MONOTONIC_RAW_APPROX` is the only one that's somewhat reasonable, but even that is supposed to be faster than a syscall. The other clocks are supposed to behave quite differently.

I am not sure what issues you are referring to here, but please note it was never the intention of the legacy-support implementation to replicate the runtime performance of the call compared to system native implementations. The aim has always only been to correctly mimic the returned information, and to that end the currently implementation for the three supported options works just fine. e.g. on macOS12 using the system calls

```
Oberon ~/Projects/MacPorts/legacy-support > test/test_time 
0 0 1000
CLOCK_REALTIME (0)      0 1685971665130425000
CLOCK_REALTIME (0)      0 1685971665130429000
CLOCK_REALTIME (0)      0 1685971665130431000
CLOCK_REALTIME (0)      0 1685971665130434000
CLOCK_REALTIME (0)      0 1685971665130436000
CLOCK_REALTIME (0)      0 1685971665130438000
CLOCK_REALTIME (0)      0 1685971665130440000
CLOCK_REALTIME (0)      0 1685971665130443000
CLOCK_REALTIME (0)      0 1685971665130445000
0 0 1000
CLOCK_MONOTONIC (6)     0 192312899137000
CLOCK_MONOTONIC (6)     0 192312899139000
CLOCK_MONOTONIC (6)     0 192312899142000
CLOCK_MONOTONIC (6)     0 192312899144000
CLOCK_MONOTONIC (6)     0 192312899146000
CLOCK_MONOTONIC (6)     0 192312899149000
CLOCK_MONOTONIC (6)     0 192312899152000
CLOCK_MONOTONIC (6)     0 192312899154000
CLOCK_MONOTONIC (6)     0 192312899156000
0 0 1
CLOCK_MONOTONIC_RAW (4) 0 192322608708268
CLOCK_MONOTONIC_RAW (4) 0 192322608710669
CLOCK_MONOTONIC_RAW (4) 0 192322608712860
CLOCK_MONOTONIC_RAW (4) 0 192322608715243
CLOCK_MONOTONIC_RAW (4) 0 192322608717490
CLOCK_MONOTONIC_RAW (4) 0 192322608719790
CLOCK_MONOTONIC_RAW (4) 0 192322608721985
CLOCK_MONOTONIC_RAW (4) 0 192322608724189
CLOCK_MONOTONIC_RAW (4) 0 192322608726370
```

whereas forcing the use of the legacy support methods 

```
Oberon ~/Projects/MacPorts/legacy-support > test/test_time     
0 0 1000
CLOCK_REALTIME (0)      0 1685971728474736000
CLOCK_REALTIME (0)      0 1685971728474740000
CLOCK_REALTIME (0)      0 1685971728474743000
CLOCK_REALTIME (0)      0 1685971728474745000
CLOCK_REALTIME (0)      0 1685971728474748000
CLOCK_REALTIME (0)      0 1685971728474750000
CLOCK_REALTIME (0)      0 1685971728474753000
CLOCK_REALTIME (0)      0 1685971728474755000
CLOCK_REALTIME (0)      0 1685971728474757000
0 0 1000
CLOCK_MONOTONIC (6)     0 192385956279000
CLOCK_MONOTONIC (6)     0 192385956282000
CLOCK_MONOTONIC (6)     0 192385956284000
CLOCK_MONOTONIC (6)     0 192385956288000
CLOCK_MONOTONIC (6)     0 192385956290000
CLOCK_MONOTONIC (6)     0 192385956292000
CLOCK_MONOTONIC (6)     0 192385956295000
CLOCK_MONOTONIC (6)     0 192385956297000
CLOCK_MONOTONIC (6)     0 192385956300000
0 0 1
CLOCK_MONOTONIC_RAW (4) 0 192385956304837
CLOCK_MONOTONIC_RAW (4) 0 192385956307430
CLOCK_MONOTONIC_RAW (4) 0 192385956309940
CLOCK_MONOTONIC_RAW (4) 0 192385956312797
CLOCK_MONOTONIC_RAW (4) 0 192385956315244
CLOCK_MONOTONIC_RAW (4) 0 192385956317668
CLOCK_MONOTONIC_RAW (4) 0 192385956320070
CLOCK_MONOTONIC_RAW (4) 0 192385956322664
CLOCK_MONOTONIC_RAW (4) 0 192385956325162
```

so the legacy support method works just as intended for these options.

**Comment by cjones051073** [comment]
So, running the updates here, first using the system libraries on macOS12

```
Oberon ~/Projects/MacPorts/legacy-support > test/test_time 
0 0 1000
CLOCK_REALTIME (0)      0 1685972302169033000
CLOCK_REALTIME (0)      0 1685972302169047000
CLOCK_REALTIME (0)      0 1685972302169049000
CLOCK_REALTIME (0)      0 1685972302169051000
CLOCK_REALTIME (0)      0 1685972302169053000
CLOCK_REALTIME (0)      0 1685972302169056000
CLOCK_REALTIME (0)      0 1685972302169058000
CLOCK_REALTIME (0)      0 1685972302169060000
CLOCK_REALTIME (0)      0 1685972302169062000
0 0 1000
CLOCK_MONOTONIC (6)     0 192949937754000
CLOCK_MONOTONIC (6)     0 192949937757000
CLOCK_MONOTONIC (6)     0 192949937759000
CLOCK_MONOTONIC (6)     0 192949937761000
CLOCK_MONOTONIC (6)     0 192949937763000
CLOCK_MONOTONIC (6)     0 192949937765000
CLOCK_MONOTONIC (6)     0 192949937768000
CLOCK_MONOTONIC (6)     0 192949937770000
CLOCK_MONOTONIC (6)     0 192949937772000
0 0 1
CLOCK_MONOTONIC_RAW (4) 0 192959648801346
CLOCK_MONOTONIC_RAW (4) 0 192959648803679
CLOCK_MONOTONIC_RAW (4) 0 192959648805866
CLOCK_MONOTONIC_RAW (4) 0 192959648807996
CLOCK_MONOTONIC_RAW (4) 0 192959648810081
CLOCK_MONOTONIC_RAW (4) 0 192959648812169
CLOCK_MONOTONIC_RAW (4) 0 192959648814657
CLOCK_MONOTONIC_RAW (4) 0 192959648816927
CLOCK_MONOTONIC_RAW (4) 0 192959648819052
0 0 1
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192959648761919
0 0 1
CLOCK_UPTIME_RAW (8) 0 192959648845122
CLOCK_UPTIME_RAW (8) 0 192959648847559
CLOCK_UPTIME_RAW (8) 0 192959648849797
CLOCK_UPTIME_RAW (8) 0 192959648851899
CLOCK_UPTIME_RAW (8) 0 192959648853995
CLOCK_UPTIME_RAW (8) 0 192959648856190
CLOCK_UPTIME_RAW (8) 0 192959648858598
CLOCK_UPTIME_RAW (8) 0 192959648860799
CLOCK_UPTIME_RAW (8) 0 192959648862895
0 0 1
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
CLOCK_UPTIME_RAW_APPROX (9) 0 192959648761919
0 0 1000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2601000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2606000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2609000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2612000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2615000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2618000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2620000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2623000
CLOCK_PROCESS_CPUTIME_ID (12) 0 2626000
0 0 1
CLOCK_THREAD_CPUTIME_ID (16) 0 2631828
CLOCK_THREAD_CPUTIME_ID (16) 0 2634569
CLOCK_THREAD_CPUTIME_ID (16) 0 2636990
CLOCK_THREAD_CPUTIME_ID (16) 0 2639401
CLOCK_THREAD_CPUTIME_ID (16) 0 2641997
CLOCK_THREAD_CPUTIME_ID (16) 0 2644509
CLOCK_THREAD_CPUTIME_ID (16) 0 2646900
CLOCK_THREAD_CPUTIME_ID (16) 0 2649325
CLOCK_THREAD_CPUTIME_ID (16) 0 2651715
```

and then using the legacy support implementations

```
Oberon ~/Projects/MacPorts/legacy-support > test/test_time 
0 0 1000
CLOCK_REALTIME (0)      0 1685972338923430000
CLOCK_REALTIME (0)      0 1685972338923434000
CLOCK_REALTIME (0)      0 1685972338923436000
CLOCK_REALTIME (0)      0 1685972338923438000
CLOCK_REALTIME (0)      0 1685972338923441000
CLOCK_REALTIME (0)      0 1685972338923443000
CLOCK_REALTIME (0)      0 1685972338923445000
CLOCK_REALTIME (0)      0 1685972338923447000
CLOCK_REALTIME (0)      0 1685972338923449000
0 0 1000
CLOCK_MONOTONIC (6)     0 192996404721000
CLOCK_MONOTONIC (6)     0 192996404724000
CLOCK_MONOTONIC (6)     0 192996404726000
CLOCK_MONOTONIC (6)     0 192996404728000
CLOCK_MONOTONIC (6)     0 192996404730000
CLOCK_MONOTONIC (6)     0 192996404732000
CLOCK_MONOTONIC (6)     0 192996404735000
CLOCK_MONOTONIC (6)     0 192996404737000
CLOCK_MONOTONIC (6)     0 192996404739000
0 0 1
CLOCK_MONOTONIC_RAW (4) 0 192996404743557
CLOCK_MONOTONIC_RAW (4) 0 192996404745863
CLOCK_MONOTONIC_RAW (4) 0 192996404747971
CLOCK_MONOTONIC_RAW (4) 0 192996404750166
CLOCK_MONOTONIC_RAW (4) 0 192996404753328
CLOCK_MONOTONIC_RAW (4) 0 192996404755494
CLOCK_MONOTONIC_RAW (4) 0 192996404757593
CLOCK_MONOTONIC_RAW (4) 0 192996404759718
CLOCK_MONOTONIC_RAW (4) 0 192996404761960
-1 140701946877760 140703603219378
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404766972
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404769298
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404771499
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404774325
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404776754
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404778943
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404781083
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404783230
CLOCK_MONOTONIC_RAW_APPROX (5) 0 192996404785714
-1 140701946877760 140703603219378
CLOCK_UPTIME_RAW (8) 0 192996404790251
CLOCK_UPTIME_RAW (8) 0 192996404792531
CLOCK_UPTIME_RAW (8) 0 192996404794636
CLOCK_UPTIME_RAW (8) 0 192996404796982
CLOCK_UPTIME_RAW (8) 0 192996404799195
CLOCK_UPTIME_RAW (8) 0 192996404801322
CLOCK_UPTIME_RAW (8) 0 192996404803439
CLOCK_UPTIME_RAW (8) 0 192996404805541
CLOCK_UPTIME_RAW (8) 0 192996404807947
-1 140701946877760 140703603219378
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404812423
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404814740
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404816908
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404819151
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404821379
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404823542
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404825684
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404827796
CLOCK_UPTIME_RAW_APPROX (9) 0 192996404830014
-1 140701946877760 140703603219378
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404834486
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404836831
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404839088
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404841408
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404843655
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404845789
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404847916
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404850038
CLOCK_PROCESS_CPUTIME_ID (12) 0 192996404852546
-1 140701946877760 140703603219378
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404856979
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404859293
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404861731
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404864318
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404866499
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404868639
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404870773
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404873283
CLOCK_THREAD_CPUTIME_ID (16) 0 192996404875544
```

I have some observations

1. @catap You need to update `clock_getres` to return the correct time resolutions for the new types.
2. There is more variation in the legacy support implementation for CLOCK_MONOTONIC_RAW_APPROX and CLOCK_UPTIME_RAW_APPROX than the system library shows. Note sure if this is an issue or not ...
3. The scale of the values returned for CLOCK_PROCESS_CPUTIME_ID and  LOCK_THREAD_CPUTIME_ID are completely different. I think these time types at least might require a specific implementation in the legacy support version that better mirrors what the system is returning.

**Review by cjones051073 — CHANGES_REQUESTED** [review]
See https://github.com/macports/macports-legacy-support/pull/58#issuecomment-1576838558

**Comment by jmroot** [comment]
> @jmroot anyway, wrong value which increases is much better than error or no value, isn't it?

Not necessarily. Incorrect results at runtime can be just as bad or worse. It depends on how the clock is being used.

**Comment by cjones051073** [comment]
> > @jmroot anyway, wrong value which increases is much better than error or no value, isn't it?
> 
> Not necessarily. Incorrect results at runtime can be just as bad or worse. It depends on how the clock is being used.

Agreed, the results have to be correct. Returning a value thats garbage is worse than not doing anything. For instance, the values currently returned for the two CPUTIME types are currently just plain wrong. They should either be fixed, or we should not pretend we can implement them and they should be removed.

**Comment by jmroot** [comment]
> so the legacy support method works just as intended for these options.

You can't test the correctness of these clocks just by looping. The correct behaviour of `CLOCK_MONOTONIC` and `CLOCK_UPTIME_RAW` for example can only be confirmed by putting the system to sleep for a while.

**Comment by cjones051073** [comment]
> > 3\. There is more variation in the legacy support implementation for CLOCK_MONOTONIC_RAW_APPROX and CLOCK_UPTIME_RAW_APPROX than the system library shows. Note sure if this is an issue or not ...
> 
> The whole point of these clocks is that they return a cached value and so get you a result much faster than doing a syscall. The only reason you would use them is if speed is critical and accuracy is less so.

Yes, thats what I suspected. Then probably here we would want an implementation that does the same, otherwise it could result in end users getting unexpected results.

**Comment by jmroot** [comment]
> I don't make any correctness statement for the new types added here, so the tests for these need to be done. However, for the currently implemented types I believe they do respond correctly in that scenario. So I believe `CLOCK_MONOTONIC` behaves consistently w.r.t. the system implementation.

I'm pretty sure the current implementation of `CLOCK_MONOTONIC` and `CLOCK_MONOTONIC_RAW` behaves the way that `CLOCK_UPTIME_RAW` is supposed to, i.e. not incrementing while the system is asleep.

**Comment by cjones051073** [comment]
> > I don't make any correctness statement for the new types added here, so the tests for these need to be done. However, for the currently implemented types I believe they do respond correctly in that scenario. So I believe `CLOCK_MONOTONIC` behaves consistently w.r.t. the system implementation.
> 
> I'm pretty sure the current implementation of `CLOCK_MONOTONIC` and `CLOCK_MONOTONIC_RAW` behaves the way that `CLOCK_UPTIME_RAW` is supposed to, i.e. not incrementing while the system is asleep.

OK, I will have to test this later on. All I can say is my machine regularly goes to sleep for extended periods, but nevertheless I have never (I think) seen the legacy implementation differ from the system one in terms of the scale of the values returned. If as you say the values did not take step times I would not expect the values I see to be as close as they are.

**Comment by cjones051073** [comment]
> > > I don't make any correctness statement for the new types added here, so the tests for these need to be done. However, for the currently implemented types I believe they do respond correctly in that scenario. So I believe `CLOCK_MONOTONIC` behaves consistently w.r.t. the system implementation.
> > 
> > 
> > I'm pretty sure the current implementation of `CLOCK_MONOTONIC` and `CLOCK_MONOTONIC_RAW` behaves the way that `CLOCK_UPTIME_RAW` is supposed to, i.e. not incrementing while the system is asleep.
> 
> OK, I will have to test this later on. All I can say is my machine regularly goes to sleep for extended periods, but nevertheless I have never (I think) seen the legacy implementation differ from the system one in terms of the scale of the values returned. If as you say the values did not take step times I would not expect the values I see to be as close as they are.

Hmm, in retrospect maybe the values aren't as close as I thought they where....

**Comment by catap** [comment]
> `libfaketime` might provide some of the missing implementation, assuming upstream did their homework. (But not sure how well it mimics the real APIs though, so perhaps theirs aren't quite perfect either...)

Seems that they decided to take a rest instead homework: https://github.com/wolfcw/libfaketime/blob/master/src/libfaketime.c#L3399-L3411

**Comment by jmroot** [comment]
Apple's implementations, for reference: https://github.com/apple-oss-distributions/Libc/blob/7861c72b1692b65f79c03f21a8a1a8e51e14c843/gen/clock_gettime.c

In particular, their fallback for `CLOCK_MONOTONIC` is just `gettimeofday()` minus `sysctlbyname("kern.boottime")`.

**Comment by catap** [comment]
@cjones051073 , @jmroot just pushed a new version. Now it should be close enough.

I haven't round `_APPROX` calls, but added some increased nanos to `CLOCK_THREAD_CPUTIME_ID`. Anyway, I have no idea how to get real thread usage.

**Comment by cjones051073** [comment]
> @cjones051073 , @jmroot just pushed a new version. Now it should be close enough.
> 
> I haven't round `_APPROX` calls, but added some increased nanos to `CLOCK_THREAD_CPUTIME_ID`. Anyway, I have no idea how to get real thread usage.

Running your latest version, there are still significant differences between the reference implementation for the two CPUTIME types, and what the legacy support implementation does.

Pretending to be able to implement this, but then give the wrong values, is way worse than not implementing it at all. So unless a real implementation for these two can be found then they should be just removed.

**Comment by cjones051073** [comment]
@catap ping. Please either fix, or failing that remove, the two CPUTIME methods so this can be further tested.

**Comment by catap** [comment]
@cjones051073 I'll take a look on it later this week. I haven't forgotten about that but I had quite a flue that slowdown me a lot.

**Comment by catap** [comment]
@cjones051073 I've removed ugly hack to emulate `CLOCK_THREAD_CPUTIME_ID`. The right way is (some how) make a calls similar to:

https://github.com/opensource-apple/xnu/blob/xnu-2782.1.97/osfmk/kern/thread.c#L1448-L1465

anyway, I have no idea how can I do it from user space.

**Comment by catap** [comment]
And sorry for long response. It was much longer that I expected.

**Comment by barracuda156** [comment]
What is the status of the PR? We need this fix. For example, `spice-server` is broken otherwise: https://trac.macports.org/ticket/67983

**Comment by jmroot** [comment]
The status as far as spice-server is concerned is that this won't fix it. There is no way (that we currently know of) outside the kernel to get at the per-thread information needed to implement `CLOCK_THREAD_CPUTIME_ID` on older OS versions.

**Comment by catap** [comment]
BTW I've removed test for `CLOCK_THREAD_CPUTIME_ID`.

**Comment by mascguy** [comment]
> BTW I've removed test for `CLOCK_THREAD_CPUTIME_ID`.

Since we apparently can't emulate this (without kernel support), should all support for it be removed at this point?

**Comment by catap** [comment]
@mascguy pushed a version where all traces of `CLOCK_THREAD_CPUTIME_ID` is removed. I've also rebased it into the last master.

**Comment by mascguy** [comment]
> @mascguy pushed a version where all traces of `CLOCK_THREAD_CPUTIME_ID` is removed. I've also rebased it into the last master.

Great, thanks Kirill!

@cjones051073 and @jmroot, thoughts on what remains? Are we good, not good, ...?

**Comment by mascguy** [comment]
Rebased against master, to include the latest change related to testing of `fstatat64`.

**Comment by catap** [comment]
Thanks, Christopher!

**Comment by mascguy** [comment]
@cjones051073 Chris, this would be a great addition. What do you think at this point?

**Comment by mascguy** [comment]
Beautiful, thanks for giving this a thumbs-up Chris! Merging.

**Pull request merged**
